name: update-flake-lock

on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * 0'

permissions:
  contents: write
  pull-requests: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262

      - uses: cachix/install-nix-action@08dcb3a5e62fa31e2da3d490afc4176ef55ecd72

      - name: Update flake.lock
        uses: DeterminateSystems/update-flake-lock@a2bbe0274e3a0c4194390a1e445f734c597ebc37
        with:
          pr-title: "chore: update flake.lock"
          pr-labels: |
            dependencies
            automated
