name: update-flake-lock

on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * 0'

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262

      - uses: DeterminateSystems/nix-installer-action@v16

      - uses: DeterminateSystems/magic-nix-cache-action@87b14cf437d03d37989d87f0fa5ce4f5dc1a330b

      - name: Update flake.lock
        uses: DeterminateSystems/update-flake-lock@v24
        with:
          pr-title: "chore: update flake.lock"
          pr-labels: |
            dependencies
            automated
