name: weekly-compat

on:
  schedule:
    - cron: '0 0 * * 1'
  workflow_dispatch:

jobs:
  lix-compat:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262

      - name: Install Lix
        run: |
          curl -sSf -L https://install.lix.systems/lix | sh -s -- install --no-confirm --no-modify-profile
          . /nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh

      - name: lix flake check
        run: nix flake check --allow-import-from-derivation

  sbom:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262

      - uses: cachix/install-nix-action@08dcb3a5e62fa31e2da3d490afc4176ef55ecd72
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: generate SBOM
        run: |
          nix build .#homeConfigurations.linux.activationPackage --no-link
          target="$(nix path-info .#homeConfigurations.linux.activationPackage)"
          nix run nixpkgs#sbomnix -- "$target" --cdx sbom.cdx.json
          ls -la sbom.cdx.json

      - name: upload SBOM
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02
        with:
          name: sbom
          path: sbom.cdx.json
